	tinyMCE.init({
		mode : "textareas",
		theme : "advanced",
		skin : "o2k7",
		skin_variant : "black",
		content_css : "../styles/blucent/css/editor.css",
		theme_advanced_font_sizes: "10px,12px,13px,14px,16px,18px,20px",
		font_size_style_values : "10px,12px,13px,14px,16px,18px,20px",
		plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
		style_formats : [
		{title : 'Label', inline : 'span', classes : 'label'},
		{title : 'Label Success', inline : 'span', classes : 'label label-success'},
		{title : 'Label Warning', inline : 'span', classes : 'label label-warning'},
		{title : 'Label Important', inline : 'span', classes : 'label label-important'},
		{title : 'Label Info', inline : 'span', classes : 'label label-info'},
		{title : 'Label Inverse', inline : 'span', classes : 'label label-inverse'},
		{title : 'Lead paragraph', block : 'p', classes : 'lead'},
		{title : 'Div alert-error', block : 'div', classes : 'alert alert-error'},
		{title : 'Div alert-success', block : 'div', classes : 'alert alert-success'},
		{title : 'Div alert-info', block : 'div', classes : 'alert alert-info'},
		{title : 'Div alert-info', block : 'div', classes : 'alert alert-info'},
		{title : 'Div brightBox', block : 'div', classes : 'brightBox'},
		{title : 'Div darkBox', block : 'div', classes : 'darkBox'}
		],
	// Theme options
		theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,fontsizeselect",
		theme_advanced_buttons2 : "bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,code,syntaxhl,|,preview,|,forecolor,backcolor,|,styleprops,attribs,|,nonbreaking,template,advcode",
		theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,iespell,media,|,fullscreen",
		theme_advanced_buttons4 : "",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_styles : "img-rounded=img-rounded;img-circle=img-circle;img-polaroid=img-polaroid;a btn=btn;a btn-primary=btn btn-primary;a btn-info=btn btn-info;a btn-success=btn btn-success;a btn-warning=btn btn-warning;a btn-danger=btn btn-danger;a btn-inverse=btn btn-inverse;a btn-link=btn btn-link",
		theme_advanced_resizing : true,
		theme_advanced_resize_horizontal : false,
		plugin_preview_width : "900",
		width : "100%",
		height : "480",
		editor_selector : "mceEditor",
		relative_urls : false,
		remove_script_host : true,
		external_image_list_url : "core/imagelist.php",
		template_external_list_url : "core/templatelist.php",
		extended_valid_elements : "textarea[cols|rows|disabled|name|readonly|class]",
		visual : true,
		language : "de"
	});
	
	
	tinyMCE.init({
		mode : "textareas",
		theme : "advanced",
		skin : "o2k7",
		skin_variant : "black",
		content_css : "../styles/blucent/css/editor.css",
		theme_advanced_font_sizes: "10px,12px,13px,14px,16px,18px,20px",
		font_size_style_values : "10px,12px,13px,14px,16px,18px,20px",
		plugins : "style,advlink,advimage,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template",
		style_formats : [
		{title : 'Label', inline : 'span', classes : 'label'},
		{title : 'Label Success', inline : 'span', classes : 'label label-success'},
		{title : 'Label Warning', inline : 'span', classes : 'label label-warning'},
		{title : 'Label Important', inline : 'span', classes : 'label label-important'},
		{title : 'Label Info', inline : 'span', classes : 'label label-info'},
		{title : 'Label Inverse', inline : 'span', classes : 'label label-inverse'},
		{title : 'Lead paragraph', block : 'p', classes : 'lead'},
		{title : 'Div alert-error', block : 'div', classes : 'alert alert-error'},
		{title : 'Div alert-success', block : 'div', classes : 'alert alert-success'},
		{title : 'Div alert-info', block : 'div', classes : 'alert alert-info'},
		{title : 'Div alert-info', block : 'div', classes : 'alert alert-info'},
		{title : 'Div brightBox', block : 'div', classes : 'brightBox'},
		{title : 'Div darkBox', block : 'div', classes : 'darkBox'}
		],
	// Theme options
		theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,|,styleselect,formatselect,forecolor,backcolor",
		theme_advanced_buttons2 : "bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,code,|,preview",
		theme_advanced_buttons3 : 
		"hr,removeformat,visualaid,|,sub,sup,charmap,|,print,|,fullscreen,template",
		theme_advanced_toolbar_location : "top",
		theme_advanced_toolbar_align : "left",
		theme_advanced_statusbar_location : "bottom",
		theme_advanced_resizing : true,
		theme_advanced_resize_horizontal : false,
		width : "100%",
		height : "350",
		editor_selector : "mceEditor_small",
		relative_urls : false,
		remove_script_host : true,
		external_image_list_url : "core/imagelist.php",
		template_external_list_url : "core/templatelist.php",
		visual : true,
		language : "de"
	});